version: '3.8'

services:
  app:
    build: 
      context: /home/ubuntu/projeto_ada_gabriela/projetoFlask
      dockerfile: Dockerfile
    ports:
      - "2000:2000"
    volumes:
      - /home/ubuntu/projeto_ada_gabriela/projetoFlask:/app
    depends_on:
      - db
    networks:
      - projetoada

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./backup:/backup
      - /home/ubuntu/projeto_ada_gabriela/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: "minhasenha"
      MYSQL_DATABASE: "flaskdocker"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "minhasenha"
    ports:
      - "3306:3306"
    networks:
      - projetoada

networks:
  projetoada:

volumes:
  db_data:
