version: '3.8'

services:
  flask_app:
    build:
      context: ./projetoFlask
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mysql_api_container
    environment:
      - FLASK_ENV=development
    networks:
      - app_network

  mysql_api_container:
    build:
      context: ./projetomysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: minhasenha
      MYSQL_DATABASE: flaskdocker
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql
      - ./backup:/backup
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_db:
